######################################################################
# Automatically generated by qmake (2.00a) Wed Aug 9 01:40:07 2006
######################################################################

TEMPLATE = vcapp
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .
QT += xml

# Input
HEADERS += VSPTree.h
SOURCES += main.cpp VSPTree.cpp
